name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: windows-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Install MinGW (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw

      - name: Set GCC/MinGW as the compiler (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          $env:PATH = 'C:\tools\mingw64\bin;' + $env:PATH
          $env:CC = 'gcc'
          $env:CXX = 'g++'

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: >
          cmake -G "MinGW Makefiles"
          -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Configure CMake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: >
          cmake
          -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Prepare release assets (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p release_assets
          cp -r ${{ github.workspace }}/resources release_assets/
          cp ${{ steps.strings.outputs.build-output-dir }}/celestial_roll release_assets/
          zip -r ${{ matrix.os }}-release.zip release_assets
        shell: bash

      - name: Prepare release assets (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir release_assets
          cp -r ${{ github.workspace }}/resources release_assets/
          cp ${{ steps.strings.outputs.build-output-dir }}/celestial_roll.exe release_assets/
          Compress-Archive -Path release_assets/* -DestinationPath ${{ matrix.os }}-release.zip
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-release-assets
          path: ${{ matrix.os }}-release.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download Linux assets
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-release-assets

      - name: Download Windows assets
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-release-assets

      - name: Delete existing release
        run: |
          gh release delete ${{ github.ref_name }} --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Delete existing tag
        run: |
          git push --delete origin ${{ github.ref_name }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ubuntu-latest-release.zip
          asset_name: linux-release.zip
          asset_content_type: application/zip

      - name: Upload Windows release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: windows-latest-release.zip
          asset_name: windows-release.zip
          asset_content_type: application/zip
